import type { Metadata } from "next";
import "@/app/globals.css";
import NavBar from "@/components/Nav";
import { Footer } from "@/components/Footer";
import JoinUs from "@/components/JoinUs";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <NavBar />
      {children}
      <JoinUs />
      <Footer />
    </>
  );
}
